<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap-tuning.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js') ?>

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('ZF2 Demo for ZFMeetup') ?></a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                <?php if ($this->plugin('zfcUserIdentity')->getAuthService()->hasIdentity()) { ?>
              <li><a href="<?php echo $this->url('admin/articles') ?>"><i class="icon-file icon-white"></i> Manage Articles</a></li>
              <li><a href="<?php //echo $this->url('admin-admins') ?>"><i class="icon-user icon-white"></i> Manage Admins</a></li>
            </ul>
            <ul class="nav pull-right">
              <li><span>Logged as <?php echo $this->plugin('zfcUserIdentity')->getAuthService()->getIdentity()->getEmail() ?></span></li>
              <li><a href="<?php echo $this->url('zfcuser/logout')?>">
                Logout <i class="icon-remove icon-white"></i></a></li>
            <?php } else { ?>
                </ul><ul class="nav pull-right">
                <li><a href="<?php echo $this->url('zfcuser/login')?>">
                Login <i class="icon-user icon-white"></i></a></li>
            <?php } ?>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
    
    <?php foreach ($this->messages as $message) { ?>
            <div class="alert alert-success"><?php echo $message; ?></div>
        <?php } ?>
      <?php echo $this->content; ?>

      <hr>

      <footer>
        <p>&copy; 2005 - 2012 by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
      </footer>

    </div> <!-- /container -->

  <?php echo $this->inlineScript() ?>
  </body>
</html>
