<?php $this->headTitle()->prepend($this->escapeHtml($article['name'])) ?>

<article>
    <header>
      <h2><?php echo $this->escapeHtml($article['name']) ?></h2>
      <p>
        <time datetime="<?php echo $this->escapeHtml($article['published'])?>"><?php echo $this->escapeHtml($article['published'])?></time>
        by <?php echo $this->escapeHtml($article['admin_name'])?>
      </p>
    </header>
<header>

<div>
    <?php echo $article['text']; //not escaped, we want to use HTML ?>
</div>
</article>

<h3>Comments:</h3>
<?php if ($article['comments']) { ?>
    <?php foreach ($article['comments'] as $comment) { ?>
        <div class="comment">
            <p class="comment-author">
                <?php echo $this->escapeHtml($comment['name'])?>
                <?php echo $this->escapeHtml($comment['commented_on'])?>
            </p>
            <div>
                <?php echo $this->escapeHtml($comment['text'])?>
            </div>
        </div>
    <?php } ?>
<?php } else { ?>
    <p>No comments, you can add first!</p>
<?php } ?>

<div id="comment-form">

<?php /*
if ($this->authService()->getAuth()->hasIdentity()) {
	$identity = $this->authService()->getAuth()->getIdentity();
	$commentForm->getElement('name')->setValue($identity->name);
	$commentForm->getElement('email')->setValue($identity->email);
}*/
?>

<?php echo $this->formRenderer($this->commentForm); ?>

</div>