<?php foreach ($articles as $article) { ?>
    <article>
    <header>
      <h2>
        <a href="<?php echo $this->url('blog/article', array('id' => $article['id'])) ?>">
            <?php echo $this->escapeHtml($article['name'])?>
        </a>
      </h2>
	  <p>
        <time datetime="<?php echo $this->escapeHtml($article['published'])?>"><?php echo $this->escapeHtml($article['published'])?></time>
        by <?php echo $this->escapeHtml($article['admin_name'])?>
      </p>
	</header>
    <div>
        <?php if (strpos($article['text'], '<!-- more -->') !== false) {
        	echo substr($article['text'], 0, strpos($article['text'], '<!-- more -->')); //not escaped, we want to use HTML
        } else {
        	echo $article['text']; //not escaped, we want to use HTML
        } ?>
    </div>
    <div>Comments: <?php echo $this->escapeHtml($article['comments_count'])?> </div>
    
    </article>
    <hr/>
<?php } ?>

<?php echo $this->paginationControl($articles, 'Sliding', 'blog/pagination_control.phtml'); ?>